id: IACE6C000
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T04:42:10+00:00'
last_modified: '2022-06-08T02:19:29.494351+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ65548
  title: བདེ་སྨོན་ཞིང་མཆོག་སྒོ་འབྱེད་མཆོད་ཆོག་ཏུ་བསྒྲིགས་པ་འཆི་མེད་དཔལ་སྟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1C7A:
      image_group_id: I4CZ75530
      title: ''
      total_pages: 294
      order: 1
      base_file: 1C7A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
